# Copyright (c) IBM Corporation 2020

# IBM collection namespace
namespace: freemanlatrell

# Ansible collection to work with z/OS based on z/OSMF
name: cloud_provisioning

# The collection version
version: 2.2.8

# Collection README file
readme: README.md

# Contributors
authors:
  - "Yang Cao <caoy@cn.ibm.com>"
  - "Yun Juan Yang <yunyyang@cn.ibm.com>"
  - "Hiren Shah <hiren@us.ibm.com>"
  - "Allen Zhou <xiao-yu.zhou@ibm.com>"
  - "Latrell Freeman <ldfreema@us.ibm.com>"
  - "Scott Shuffler <scott.shuffler@ibm.com>"

# Description
description: Ansible collection consisting of modules and roles to work with Cloud Provisioning and Management.

# License
license:
  - GPL-3.0-only
  - Apache-2.0

# The URL of the originating SCM repository
repository: https://github.com/zoscb/ibm_zos_zosmf

# The URL to any online docs
documentation: https://ibm.github.io/ibm_zos_zosmf/index.html

# The URL to the collection issue tracker
issues: https://github.com/IBM/ibm_zos_zosmf/issues
