# Copyright (c) IBM Corporation 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# tasks file for cics

- name: Set variables
  set_fact:
    HOST_IP: "{{ instance_info_json['registry-info'] | json_query('variables[?name == `DFH_REGION_HOSTNAME`]') | join(' ') }}"
    HTTPS_PORT_OBJ: "{{ instance_info_json['registry-info'] | json_query('variables[?name == `DFH_REGION_HTTPS`]') | join(' ') }}"
    CICS_DROP_APP_DIR: "{{ instance_info_json['registry-info'] | json_query('variables[?name == `DFH_REGION_ZFS_DIRECTORY`]') | join(' ') }}"

- name: Install CICS application - Create USS empty file
  uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/restfiles/fs{{ CICS_DROP_APP_DIR.value }}/workdir/DFHWLP/wlp/usr/servers/defaultServer/dropins/{{ app_file_name }}"
    return_content: yes
    user: "{{ zmf_user }}"
    password: "{{ zmf_password  }}"
    force_basic_auth: yes
    headers:
      X-CSRF-ZOSMF-HEADER: script
      Content-Type: "application/json"
    method: POST
    validate_certs: no
    status_code: 201, 500 # 500 if file already exist
    body_format: json
    body: '{"type":"file","mode":"RWXRW-RW-"}'
  delegate_to: localhost

- name: Install CICS application - Write application binary to USS file
  uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/restfiles/fs{{ CICS_DROP_APP_DIR.value }}/workdir/DFHWLP/wlp/usr/servers/defaultServer/dropins/{{ app_file_name }}"
    return_content: yes
    user: "{{ zmf_user }}"
    password: "{{ zmf_password  }}"
    force_basic_auth: yes
    headers:
      X-CSRF-ZOSMF-HEADER: script
      X-IBM-Data-Type: "binary"
    method: PUT
    validate_certs: no
    status_code: "204"
    src: "{{ application_path }}"
  delegate_to: localhost
  register: results

- name: Display results
  debug:
    msg: "Your application is ready at https://{{ HOST_IP.value }}:{{HTTPS_PORT_OBJ.value}}{{app_root_uri}}"
