# Copyright (c) IBM Corporation 2020 

# Sample playbook for CFRM Policy Change scenario.
# Example:
# ansible-playbook -i hosts demo_step3.2_check_cfrm_policy_change_pending.yml

- name: check CFRM policy change pending
  hosts: mySystems
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars:
    current_dir: "{{ local_output_dir | regex_replace('/$', '') }}/CFRMChange{{ '%Y%m%d' | strftime }}"
    current_time: "{{ '%Y%m%d' | strftime }}_{{ '%H%M%S' | strftime }}"
    cfrm_policy_change: "{{ lookup('file', local_input_dir ~ '/cfrm_policy_change.txt') }}"
  tasks:
    - name: create local directory to save output
      local_action:
        module: file
        path: "{{ current_dir }}/step3_change_cfrm/3.2_check_change_pending/{{ current_time }}"
        state: "directory"
      register: demo_save_dir

    - zmf_authenticate:
        zmf_host: "{{ zmf_host }}"
        zmf_port: "{{ zmf_port }}"
        zmf_user: "{{ zmf_user }}"
        zmf_password: "{{ zmf_password }}"
      register: result_auth
      delegate_to: localhost

    - name: CF check -- D XCF,STR
      zmf_console_command:
        zmf_credential: "{{ result_auth }}"
        console_cmd: "D XCF,STR"
        console_system: "{{ inventory_hostname }}"
        console_save_output_localpath: "{{ demo_save_dir.path }}"
      register: result
      delegate_to: localhost

    - set_fact:
        policy_change_pending: []
    - set_fact:
        policy_change_pending: "{{ policy_change_pending + [[result.cmd_response[idx - 2], result.cmd_response[idx - 1], item]] }}"
      when: item.find('POLICY CHANGE PENDING') > -1
      loop: "{{ result.cmd_response }}"
      loop_control:
        index_var: idx

    - name: display pending structures
      debug: var=policy_change_pending
      when: policy_change_pending != []
    
    - name: display result
      debug: msg="Step3.2 Check CFRM Policy Change Pending is completed. Manually fix the pending and run Step3.2 again, or Approve and continue to run Step3.3 to test CFRM structure REALLOCATE process."
      when: policy_change_pending != []

    - name: display result
      debug: msg="Step3.2 Check CFRM Policy Change Pending is completed. No pending is found. Approve and continue to run Step3.3 to test CFRM structure REALLOCATE process."
      when: policy_change_pending == []