# Copyright (c) IBM Corporation 2020 

# Sample playbook for CFRM Policy Change scenario.
# Example:
# ansible-playbook -i hosts demo_step2_check_system_status_before_change.yml

- name: check system status before policy change
  hosts: mySystems
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars:
    current_dir: "{{ local_output_dir | regex_replace('/$', '') }}/CFRMChange{{ '%Y%m%d' | strftime }}"
    current_time: "{{ '%Y%m%d' | strftime }}_{{ '%H%M%S' | strftime }}"
  tasks:
    - name: create local directory to save output
      local_action:
        module: file
        path: "{{ current_dir }}/step2_system_check/{{ current_time }}"
        state: "directory"
      register: demo_save_dir

    - zmf_authenticate:
        zmf_host: "{{ zmf_host }}"
        zmf_port: "{{ zmf_port }}"
        zmf_user: "{{ zmf_user }}"
        zmf_password: "{{ zmf_password }}"
      register: result_auth
      delegate_to: localhost

    - name: CF check -- D XCF,POL,TYPE=CFRM
      zmf_console_command:
        zmf_credential: "{{ result_auth }}"
        console_cmd: "D XCF,POL,TYPE=CFRM"
        console_system: "{{ inventory_hostname }}"
        console_save_output_localpath: "{{ demo_save_dir.path }}"
      delegate_to: localhost

    - name: CF check -- D CF
      zmf_console_command:
        zmf_credential: "{{ result_auth }}"
        console_cmd: "D CF"
        console_system: "{{ inventory_hostname }}"
        console_save_output_localpath: "{{ demo_save_dir.path }}"
      delegate_to: localhost

    - name: CF check -- D XCF,CF,CFNAME=ALL
      zmf_console_command:
        zmf_credential: "{{ result_auth }}"
        console_cmd: "D XCF,CF,CFNAME=ALL"
        console_system: "{{ inventory_hostname }}"
        console_save_output_localpath: "{{ demo_save_dir.path }}"
      delegate_to: localhost

    - name: CF check -- D XCF,STR
      zmf_console_command:
        zmf_credential: "{{ result_auth }}"
        console_cmd: "D XCF,STR"
        console_system: "{{ inventory_hostname }}"
        console_save_output_localpath: "{{ demo_save_dir.path }}"
      delegate_to: localhost

    - name: CF check -- D XCF,STR,STRNM=ALL
      zmf_console_command:
        zmf_credential: "{{ result_auth }}"
        console_cmd: "D XCF,STR,STRNM=ALL"
        console_system: "{{ inventory_hostname }}"
        console_save_output_localpath: "{{ demo_save_dir.path }}"
      delegate_to: localhost
    
    - name: display result
      debug: msg="Step2 System Check Before Change is completed. The responses of system check are saved in {{ demo_save_dir.path }}/"
