# Copyright (c) IBM Corporation 2020 

# Sample playbook for CFRM Policy Change scenario.
# Example:
# ansible-playbook -i hosts demo_step3.5_rebuild_failed_cfrm_structures.yml

- name: rebuild failed CFRM structures
  hosts: mySystems
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars:
    current_dir: "{{ local_output_dir | regex_replace('/$', '') }}/CFRMChange{{ '%Y%m%d' | strftime }}"
    current_time: "{{ '%Y%m%d' | strftime }}_{{ '%H%M%S' | strftime }}"
    cfrm_policy_change: "{{ lookup('file', local_input_dir ~ '/cfrm_policy_change.txt') }}"
  tasks:
    - block:
        - name: create local directory to save output
          local_action:
            module: file
            path: "{{ current_dir }}/step3_change_cfrm/3.5_rebuild"
            state: "directory"
          register: demo_save_dir

        - zmf_authenticate:
            zmf_host: "{{ zmf_host }}"
            zmf_port: "{{ zmf_port }}"
            zmf_user: "{{ zmf_user }}"
            zmf_password: "{{ zmf_password }}"
          register: result_auth
          delegate_to: localhost

        - include_tasks: demo_step3.5.1_rebuild_failed_cfrm_structures.yml
          loop: "{{ reallocate_error_structures }}"
          loop_control:
            index_var: idx
        
        - name: display result
          debug: msg="Step3.5 Rebuild Failed CFRM Structures is completed. The responses of rebuild are saved in {{ demo_save_dir.path }}."
      when: reallocate_error_structures != []

    - block:       
        - name: display result
          debug: msg="Congratulation! CFRM Policy Change is completed and successful."
      when: reallocate_error_structures == []