# Copyright (c) IBM Corporation 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# tasks file for provision_software_service
- name: Provision template
  uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/psc/{{ cpm_template_name }}/actions/run"
    return_content: yes
    user: "{{ zmf_user| trim }}"
    password: "{{ zmf_password| trim  }}"
    force_basic_auth: yes
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    method: POST
    status_code: "200"
    validate_certs: no
    body_format: json
    body: "{{ zmf_body }}"
  delegate_to: localhost
  register: provision_results

- name: Write instance information to disk
  copy:
    content: "{{ provision_results.json | to_nice_json(indent=2) }}"
    dest: "{{ instance_record_dir }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
  delegate_to: localhost
  when: file_creation|default(true)

- name: Display instance record file path
  debug:
    msg: "Instance record saved at: {{ instance_record_dir }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
  when: file_creation|default(true)

##############################################################################
# Verify workflow step status, requires the following variables:
# {{zmf_host:zmf_port}} -> z/OSMF host uri
# {{max_retry}} -> max retry count before task exit with failing status
##############################################################################
- name: Provision instance section
  include_tasks: loop_instance_provision_step_state.yml
  vars:
    instance_object_id: "{{ provision_results.json['registry-info']['object-id'] }}"
  when: file_creation|default(true)

- name: Get provisioned instance information
  uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/scr/{{ provision_results.json['registry-info']['object-id'] }}"
    method: GET
    user: "{{ zmf_user | trim  }}"
    password: "{{ zmf_password | trim  }}"
    force_basic_auth: yes
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    status_code: "200"
    validate_certs: no
    return_content: yes
  register: full_instance_json
  delegate_to: localhost

- name: Update instance information
  block:
    - name: Update fully provisioned instance information to local
      copy:
        content: '{ "registry-info" : {{ full_instance_json.json| to_nice_json(indent=2) }}}'
        dest: "{{ instance_record_dir }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
      delegate_to: localhost

    - name: Set variable for instance json file path
      set_fact:
        zosmf_instance_info: "{{ full_instance_json.json }}"
        instance_info_json_path: "{{ instance_record_dir }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
  when: file_creation|default(true)

- name: Display instance record file path
  debug:
    msg: "Instance record saved at: {{ instance_record_dir }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
  run_once: true
  when: file_creation|default(true)
