# Copyright (c) IBM Corporation 2020 

# This sample playbook demonstrates using module `zmf_dataset_copy` to copy data to a z/OS data set or member.
# Example:
# ansible-playbook -i hosts sample_module_dataset_copy.yml

- name: sample of copying data to a z/OS data set or member
  hosts: dataset
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars_prompt:
    - name: zmf_user
      prompt: "Enter your zOSMF username (skip if zmf_crt and zmf_key are supplied)"
      private: no
    - name: zmf_password
      prompt: "Enter your zOSMF password (skip if zmf_crt and zmf_key are supplied)"
      private: yes
  tasks:
    - zmf_authenticate:
        zmf_host: "{{ zmf_host }}"
        zmf_port: "{{ zmf_port }}"
        zmf_user: "{{ zmf_user }}"
        zmf_password: "{{ zmf_password }}"
      register: result_auth
      delegate_to: localhost
    - zmf_dataset_copy:
        zmf_credential: "{{ result_auth }}"
        dataset_src: "/tmp/dataset_input/member01"
        # dataset_content: "Sample profile\nTZ=EST5EDT\n"
        dataset_dest: "ZOSMF.ANSIBLE.PDS(MEMBER)"
        # dataset_src_zos: false
        # dataset_dest_volser: "VOL001"
        # dataset_src_volser: "VOL002"
        # dataset_force: true
        # dataset_create_like: "ZOSMF.ANSIBLE.MODEL"
        # dataset_data_type: "text"
        # dataset_encoding:
        #   from: ISO8859-1
        #   to: IBM-1047
        # dataset_crlf: false
        # dataset_diff: false
        # dataset_migrate_recall: "wait"
        # dataset_checksum: "93822124D6E66E2213C64B0D10800224"
      register: result
      delegate_to: localhost
    - debug: var=result